

version: 2
updates:

  # --- FRONTEND (Vue & Tailwind) ---
  - package-ecosystem: "npm"
    directory: "/Frontend" # FIX: Großbuchstabe beachten!
    schedule:
      interval: "weekly" # Sucht einmal pro Woche nach Updates
    open-pull-requests-limit: 3


  # --- BACKEND (Alexander) ---
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3


  # --- DOCKER (Infrastruktur) ---
  - package-ecosystem: "docker"
    directory: "/" #NEU: Sucht im Hauptverzeichnis nach der docker-compose.yml
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2