# CLI Befehle:
# Wichtig: Docker Desktop muss gestartet werden/laufen
 
 
##################
# Starten & Bauen
 
# docker compose up              Startet alle Container  (.YML)
# docker compose up --build      Baut die Images  und startet dann.                                     Wichtig: Nach JEDEM npm install oder Dockerfile-Änderung.
# docker compose up -d          "Detached" Modus: Container laufen im Hintergrund.                      Wenn  das Terminal für andere Befehle frei bleibnen soll.
 
 
#########################
# Stopp & Aufräumen
 
# docker compose down           Stoppt alle Container und löscht diese (-v löscht auch Volumes).        Wichtig: Volumes speichern zB Datenbank Einträge auf der Festplatte .
# docker compose stop           Pausiert den Container ohne ihn zu entfernen.                           Wie ein Shutdown. Daten bleiben erhalten.
# docker system prune           Löscht alle ungenutzten Container, Netzwerke und alten Image-Cache.     Wenn die Festplatte voll wird
# docker rm -f [container]      Löscht Container auch im laufenden Prozess
 
##################
# Fehlersuche & Leistung Analyse
 
# docker compose logs -f        Zeigt Live-Logs aller Container (oder eines speziellen: -f backend).    Zur Fehlersuche (z.B. warum stürzt die DB ab? lol).
# docker compose ps             Listet alle laufenden Container und deren Ports auf.                    Um zu checken: "Läuft der Container wirklich?"
# docker exec -it [name] sh     Öffnet ein Terminal im laufenden Container.                             Wenn direkt im Container nach Dateien gesucht wird.
 
# docker exec -it psp_database psql -U postgres -d dienstplan                                           zeigt alle tabellen
# docker compose top            Zeigt die CPU- und RAM-Last der einzelnen Container an.                 Wichtig: für Algorithmus, um zu sehen, wie viel 'Power' er verbraucht.
# docker stats                  Zeigt Live-Tabelle über den Resourcen verbrauch                         Wichtig: Um Leistung an AG-Client anzupassen
 
 
 
##################
# den neuen Postgres Ordner direkt durchsuchen
# docker exec -it psp_database psql -U postgres -d dienstplan -c "SELECT relname, relfilenode FROM pg_class WHERE relname = 'mitarbeiter';"
# lokal zu finden unter C:\...\Diplomarbeit\postgres\data\base\[Ordner-ID]\16408
 
 
 
#   Port mapping ->   Host-Port : Container-Port   WICHTIG!!!!
 
 
 
# version: '3.8'
 
 
 
# NEU: Gemeinsame Logging-Einstellung, um den Speicher von alten Laptops zu schonen (markus)
 
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "20m"       # Puffer für lange DEBUG-Sessions lol
    max-file: "5"       # 5 files * 20MB = 100MB (historie für paar Tage)
 
 
# WICHTIG: Um mit den neuen Log-Limits zu starten (Entfernt nur die Logs)
 
    # 1. docker-compose down
    # 2. docker system prune -a --volumes  
    # 3. wsl --shutdown
    # 4. optimize-vhd -Path "C:\Users\[BENUTZERNAME]\AppData\Local\Docker\wsl\main\ext4.vhdx" -Mode Full
 
# Die Befehle in Schritt 1 und 2 sorgen dafür, dass der Inhalt der virtuellen Festplatte gelöscht wird.
# Schritt 3 und 4 sorgen erst dafür, dass die Datei unter Windows tatsächlich wieder kleiner wird.
# Ohne Schritt 4 bleibt die Datei auf Windows-Ebene
 
 
services:
  # --- DATENBANK BEREICH Lukas ---
  psp_database:
    image: postgres:15
    container_name: psp_database
    restart: always
    logging: *default-logging
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data      #NEU: von named volumes zu mount gewechselt (daten werden im root gespeichert)
    healthcheck: # NEU: Prüft, ob Postgres wirklich Anfragen annimmt
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 10
 
  # --- BACKEND Alexander ---
  psp_backend:
    build: ./backend
    container_name: psp_backend
    restart: always    #NEU: Nodemon Stabilität
    logging: *default-logging
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      # WICHTIG: damit node.js die DB im Docker-Netzwerk findet
    command: npm run devStart
    environment:
      DB_HOST: psp_database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}      
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROLE_ADMIN_PASSWORD: ${DB_ROLE_ADMIN_PASSWORD}
      INITIAL_MARKUS_PASSWORD: ${INITIAL_MARKUS_PASSWORD}
    depends_on:
      psp_database:
        condition: service_healthy
    deploy:                 # <- NEU: Leistungsbegränzer verhindert einen Absturzt (Endlosschleife)
      resources:
        limits:
          cpus: '1'         # Ein Kern der CPU
          memory: 2G        # Maximum / Limit
        reservations:
          memory: 512M      # Garantierter Speicher
 
  # --- FRONTEND BEREICH für Oliver (VUE) und JD (TAILWIND)  ---
  psp_frontend:
    # HINWEIS für das Frontend:    Docker sucht hier nach dem Ordner 'Frontend' (Großschreibung beachten!)
    build: ./Frontend
    container_name: psp_frontend
    restart: on-failure:3
    logging: *default-logging
    ports:
      - "5173:5173" # Standard Vite-Port. Falls er geändert wird, hier bitte anpassen
    volumes:
      - ./Frontend:/app         # <--- SPIEGELT VUE-CODE FÜR VITE HOT RELOAD
      - /app/node_modules
   
    environment:
      # Für den fall, dass Vue wissen muss, wo das Backend läuft: 3001  !!!
      - VITE_API_URL=/api
    depends_on:
      - psp_backend
 
# Würde den Algo nicht schneller machen aber für Später als https -Standard wichtig!!  (nur wenn mehrere User den Algo gleichzeitig verwednen würden)
# darum der DEPLOY oben hinzugefügt
 
  nginx:
    image: nginx:stable-alpine
    container_name: psp_proxy
    restart: always
    logging: *default-logging
    ports:
    - "80:80"    # HTTP für Browser
    - "443:443"   # HTTPS für später
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./certs:/etc/nginx/ssl:ro    # Zertifikate
    depends_on:
    - psp_frontend
    - psp_backend