# CLI Befehle:
# Wichtig: Docker Desktop muss gestartet werden/laufen
#   docker compose up --build -d
#   docker compose down
#   docker compose logs -f backend
#   Port mapping ->   Host-Port : Container-Port   WICHTIG!!!!
 
# docker exec -it psp_database psql -U postgres -d dienstplan -c "\dt"  zeigt alle tabellen
 
# version: '3.8'
 
services:
  # --- DATENBANK BEREICH Lukas ---
  db:
    image: postgres:15
    container_name: psp_database
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  backend:
    build: ./backend
    container_name: psp_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROLE_ADMIN_PASSWORD: ${DB_ROLE_ADMIN_PASSWORD}
      INITIAL_MARKUS_PASSWORD: ${INITIAL_MARKUS_PASSWORD}
      INIT_DB: "false"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run devStart
 
  frontend:
    build: ./Frontend
    container_name: psp_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
 
volumes:
  postgres_data: