# entscheidet wo anfragen hingehen
# nginx als Reverse Proxy   Außerhalb kommt HTTPS an, Innerhalb (docker-netz) wird HTTP verwendet

events { worker_connections 1024; }

http {
    server {
        listen 80;         # umleiten von HTTP zu HTTPS
        server_name localhost;
        return 301 https://$host$request_uri;    # erzwingt HTTPS  (permanente Umleitung - verschlüsselte Version)
    }
    server {
        listen 443 ssl;
        server_name localhost;

        # Wichtig: Pfade zu den Zertifikaten im container nginx
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;

    
        # frontend-Anfragen (VUE)   - alle Anfragen gehen an den Frontend-container
        location / {
           proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
        }

        # backend-Anfragen (API)   - alle Anfragen an Express-service
       
           location /api/ {
            proxy_pass http://backend:3001/api/;

            # Wichtig: Header damit das backend die echte IP sehen kann
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;   # sagt dem backend dass HTTPS genutz wird!!
        }
    }
}