### ---------------------------------------------------------------------------
### MITARBEITER (neues Frontend-DTO)
### ---------------------------------------------------------------------------

### GET alle Mitarbeiter
GET http://localhost:3001/api/mitarbeiter

### GET Mitarbeiter nach mnr
GET http://localhost:3001/api/mitarbeiter/11


### POST Mitarbeiter anlegen (Frontend-Format)
POST http://localhost:3001/api/mitarbeiter
Content-Type: application/json

{
  "vorname": "Test",
  "nachname": "Frontend",
  "arbeitsstunden": 40,
  "springer": "Nein",
  "hauptfiliale": 6,
  "nebenfilialen": [7],

  "strasse": "Testweg 1",
  "ort": "Wien",
  "postleitzahl": "1010",
  "land": "Österreich",

  "telefon1": "+43 660 111111",
  "telefon2": "",
  "email1": "test@demo.at",
  "email2": "",

  "anmerkungen": ""
}

### PUT Mitarbeiter bearbeiten (Frontend-Format)
PUT http://localhost:3001/api/mitarbeiter/11
Content-Type: application/json

{
  "vorname": "Test-Updated",
  "nachname": "Frontend-Updated",
  "arbeitsstunden": 40,
  "springer": "Nein",
  "hauptfiliale": 7,
  "nebenfilialen": [6],

  "strasse": "Updateweg 9",
  "ort": "Wien",
  "postleitzahl": "1010",
  "land": "Österreich",

  "telefon1": "+43 660 999999",
  "email1": "update@demo.at",

  "anmerkungen": "Update Test"
}




### DELETE Mitarbeiter
DELETE http://localhost:3001/api/mitarbeiter/11


### ---------------------------------------------------------------------------
### FILIALEN (neue Routes: /api/filialen)
### ---------------------------------------------------------------------------

### GET alle Filialen
GET http://localhost:3001/api/filialen

### GET Filiale nach fnr
GET http://localhost:3001/api/filialen/6

### POST Filiale anlegen
POST http://localhost:3001/api/filialen
Content-Type: application/json

{
  "filialname": "Hartberg",
  "farbe": "#ff0000",
  "ort": "Hartberg",
  "strasse": "Hauptplatz 1",
  "plz": "8230",
  "land": "Österreich",
  "email": "hb@firma.at",
  "telefon": "+43 3332 12345",
  "algorithmid": 1
}

### PUT Filiale bearbeiten
PUT http://localhost:3001/api/filialen/6
Content-Type: application/json

{
  "filialname": "Zentrale Wien NEU",
  "farbe": "#00ff00"
}

### DELETE Filiale
DELETE http://localhost:3001/api/filialen/6


### ---------------------------------------------------------------------------
### DIENSTPLAN (bei dir: /api/dienstplan)
### ---------------------------------------------------------------------------

### POST Dienstplan generieren + speichern (neuer Ansatz mit Einzelzeilen)
POST http://localhost:3001/api/dienstplan/generate
Content-Type: application/json

{
  "jahr": 2026,
  "monat": 1
}


### DELETE Dienstplan Monat löschen
DELETE http://localhost:3001/api/dienstplan/2026/1


### GET Dienstplan für Monat abrufen
GET http://localhost:3001/api/dienstplan?jahr=2026&monat=1