

# Wird in GitHub-Actions ausgeführt
# erst in Frontend, wieder hinaus und dann ins Backend
steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semantic Release
        run: |
          cd Frontend && npx semantic-release
          cd ../Backend && npx semantic-release

          