

# Wird in GitHub-Actions ausgeführt
# erst in Frontend, wieder hinaus und dann ins Backend

name: Automated Semantic Release

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Semantic Release Dependencies
        run: |
          echo '{"private": true}' > package.json
          npm install semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github --legacy-peer-deps

      #FIX:  Ausführung isoliert pro Verzeichnis
      - name: Run Semantic Release for Frontend & Backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Frontend && npx semantic-release
          cd ../backend && npx semantic-release